### PR TITLE
region_m49 update

### PR DESCRIPTION
**Pull request by codeforIATIbot**
Codelist update, sent from [this GitHub Action build](https://github.com/codeforIATI/codelist-updater/actions/runs/2506493707).

### CODE REVIEW

**Comment by andylolz** [comment]
This definitely looks wrong.

**Review by andylolz — COMMENTED** [review]
This definitely looks wrong.

**Review by markbrough — APPROVED** [review]
Turkey changed its name at the UN to Türkiye
https://en.m.wikipedia.org/wiki/Turkey#Name

**Comment by andylolz** [comment]
Oh! Thanks for this, I had no idea about that!

In that case this is good to merge.

**Pull request merged**
