### PR TITLE
Add mapping.xml

### PR DESCRIPTION
**Pull request by andylolz**
First pass at a mapping.xml, based on this one:
https://github.com/IATI/IATI-Codelists/blob/version-2.03/mapping.xml
I’m not sure if I’ve missed anything?

### CODE REVIEW

**Review by stevieflow — APPROVED** [review]
Yep - this file will map certain vocabularies to the specific "unoffical" codelist published by codeforiati

@andylolz I'm assuming a similar file exists for mapping vocab values to "official" codeliists?

**Comment by andylolz** [comment]
> @andylolz I'm assuming a similar file exists for mapping vocab values to "official" codeliists?

Exactly, yes – it’s here:
https://github.com/IATI/IATI-Codelists/blob/version-2.03/mapping.xml

**Comment by markbrough** [comment]
Hmm I am not sure this will work for RegionM49 codelist, given that the `recipient-region/@code` for vocab=2 is not in the `code` column in that codelist (it's one of a number of other columns)?

**Comment by andylolz** [comment]
Ohhh, I see what you mean... Is it the `codeforiati:region-code` column? Hmm okay, not sure how to make that work, we might have to remove it.

**Pull request merged**
