### PR TITLE
reporting_organisation update

### PR DESCRIPTION
**Pull request by codeforIATIbot**
Codelist update, sent from [this GitHub Action build](https://github.com/codeforIATI/codelist-updater/actions/runs/801295508).

### CODE REVIEW

**Review by andylolz — APPROVED** [review]

**Comment by andylolz** [comment]
I approved this, but then realised the name is only available in French which is maybe a bit unusual?

**Review by markbrough — APPROVED** [review]

**Comment by markbrough** [comment]
@andylolz sure but this is just the name they used on their Registry account!

**Comment by andylolz** [comment]
Yeah, fair enough.

I guess my issue is: the registry doesn’t make any claims about the language of this name, whereas our codelist says it is English. But I don’t know what we can do about that.

**Comment by markbrough** [comment]
Yeah you are right, and indeed it would be nice to have bilingual codes (eg for Canada) - I guess sourced from organisation files where available? But that would probably be a bunch of work

**Comment by andylolz** [comment]
That’s an interesting idea though! You can _almost_ get that from the CSV available here:
https://org-id-finder.codeforiati.org

**Pull request merged**
